### ISSUE TITLE
Can you please push the updated version (0.9.3) to the repo?

### ISSUE THREAD

**Issue by pitsi** [fr33p0rt/kodi-plugin.video.com.pornky#3]
Please do as the title suggests, so that kodi will autoupdate the addon to its latest version.  
Asking for a friend :D
And thank you in advance :)

**Comment by fr33p0rt** [comment]
This is a low priority task. I'm working now on change with higher priority. Higher priority task should resolve this issue too. No ETA.

**Comment by pitsi** [comment]
Why is it a low priority task? With the current status, the repo contains an addon that does not work and, imho, that is enough for someone to avoid it.

**Comment by pitsi** [comment]
As mentioned in reddit, the repo has moved to gitlab and it now contains the updated version of the addon, so I am closing this.
Thank you very much.
